### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by hendersi** [volkansevim/alpha-CENTAURI#1]
Hi,

I am using alpha-CENTAURI on nanopore reads from Arabidopsis thaliana. I am trying to use your program to annotate centromere satellites. I am using Python2.7 on a MacOS Mojave.

When I run chop_to_monomers.py I get the error pasted below. The KeyError refers to one of the read names. Do you have any suggestions on what might be going wrong and how to fix it??

Best wishes, Ian Henderson

Traceback (most recent call last):
  File "/Users/ian/Desktop/CEN/Naish/alpha-CENTAURI-master/src/chop_to_monomers.py", line 79, in <module>
    parseHMMout("hmmoutF.out", "inferred_monomers_F.zzz", "F")
  File "/Users/ian/Desktop/CEN/Naish/alpha-CENTAURI-master/src/chop_to_monomers.py", line 24, in parseHMMout
    if low != 0 and high < len(seq_db[ID]) - 1:
KeyError: '9dd87eb3-2ee7-4095-8259-11414934b389'

**Comment by hendersi** [comment]
I have fixed the problem. It was caused by reads having names like this:

>9fb046eb-5946-4eec-8834-872f4755c9d1 runid=c0d9bf1e25f81816c32813953da0a77e5b46d5c1 sampleid=Nanobind_ext1 read=15875 ch=89 start_time=2019-07-26T03:29:31Z

Once I truncated read names to this format everything works fine!

>9fb046eb-5946-4eec-8834-872f4755c9d1

**Comment by volkansevim** [comment]
Glad you could work it out, Ian. :)

**Comment by hendersi** [comment]
Thanks - I’m enjoying looking into the output!!!
